max_width=100
# <unsigned integer> Default: 100
# Maximum width of each line

hard_tabs=false
# <boolean> Default: false
# Use tab characters for indentation, spaces for alignment

tab_spaces=4
# <unsigned integer> Default: 4
# Number of spaces per tab

newline_style="Auto"
# <[Auto|Windows|Unix|Native] Default: Auto
# Unix or Windows line endings

use_small_heuristics="Default"
# <[Off|Max|Default] Default: Default
# Whether to use different formatting for items and expressions if they satisfy a heuristic notion of 'small'

fn_call_width=80
# <unsigned integer> Default: 60
# Maximum width of the args of a function call before falling back to vertical formatting.

attr_fn_like_width=70
# <unsigned integer> Default: 70
# Maximum width of the args of a function-like attributes before falling back to vertical formatting.

struct_lit_width=18
# <unsigned integer> Default: 18
# Maximum width in the body of a struct lit before falling back to vertical formatting.

struct_variant_width=35
# <unsigned integer> Default: 35
# Maximum width in the body of a struct variant before falling back to vertical formatting.

array_width=60
# <unsigned integer> Default: 60
# Maximum width of an array literal before falling back to vertical formatting.

chain_width=60
# <unsigned integer> Default: 60
# Maximum length of a chain to fit on a single line.

single_line_if_else_max_width=50
# <unsigned integer> Default: 50
# Maximum line length for single line if-else expressions. A value of zero means always break if-else expressions.

reorder_imports=true
# <boolean> Default: true
# Reorder import and extern crate statements alphabetically

reorder_modules=true
# <boolean> Default: true
# Reorder module statements alphabetically in group

remove_nested_parens=true
# <boolean> Default: true
#  Remove nested parens

short_array_element_width_threshold=10
# <unsigned integer> Default: 10
# Width threshold for an array element to be considered short

match_arm_leading_pipes="Never"
# <Always|Never|Preserve] Default: Never
#  Determines whether leading pipes are emitted on match arms

fn_args_layout="Compressed"
# <Compressed|Tall|Vertical] Default: Tall
# Control the layout of arguments in a function

match_block_trailing_comma=false
# <boolean> Default: false
#  Put a trailing comma after a block based match arm (non-block arms are not affected)

edition="2024"
# <2015|2018|2021|2024] Default: 2015
# The edition of the parser (RFC 2052)

merge_derives=true
# <boolean> Default: true
# Merge multiple `# [derive(...)]` into a single one

use_try_shorthand=false
# <boolean> Default: false
#  Replace uses of the try! macro by the ? shorthand

use_field_init_shorthand=false
# <boolean> Default: false
#  Use field initialization shorthand if possible

force_explicit_abi=true
# <boolean> Default: true
#  Always print the abi for extern items

disable_all_formatting=false
# <boolean> Default: false
#  Don't reformat anything

print_misformatted_file_names=false
# <boolean> Default: false
#  Prints the names of mismatched files that were formatted. Prints the names of files that would be formated when used with `--check` mode.
